name: chronon_helm
description: A sample command-line application.
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.9.0
dependencies:
  path: ^1.9.1
  precision_stopwatch: ^1.0.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  toxic: ^1.3.4
  universal_io: ^2.2.2
  http: ^1.5.0
  yaml: ^3.1.3
  json_events: ^1.2.2
  fast_log: ^1.0.7
  chat_color: ^1.0.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
