name: chronon_helm
description: A sample command-line application.
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  precision_stopwatch: ^1.0.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  toxic: ^1.3.4
  universal_io: ^2.2.2
  ostrich: ^1.0.0+1
  window_manager: ^0.5.1
  tray_manager: ^0.5.1
  bitsdojo_window: ^0.1.6
  apple_vision_recognize_text: ^0.0.4
  http: ^1.5.0
  yaml: ^3.1.3
  json_events: ^1.2.2
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
